import pandas as pd 


data = pd.read_csv('data/poet0.csv', index_col=False)
data = data.append(pd.read_csv('data/poet20000.csv', index_col=False), ignore_index=True)
data = data.append(pd.read_csv('data/poet40000.csv', index_col=False), ignore_index=True)
data = data.append(pd.read_csv('data/poet60000.csv', index_col=False), ignore_index=True)
data = data.append(pd.read_csv('data/poet80000.csv', index_col=False), ignore_index=True)
data = data.append(pd.read_csv('data/poet100000.csv', index_col=False), ignore_index=True)
data = data.append(pd.read_csv('data/poet120000.csv', index_col=False), ignore_index=True)
data = data.append(pd.read_csv('data/poet140000.csv', index_col=False), ignore_index=True)
data = data.append(pd.read_csv('data/poet160000.csv', index_col=False), ignore_index=True)
data = data.append(pd.read_csv('data/poet180000.csv', index_col=False), ignore_index=True)
data = data.append(pd.read_csv('data/poet200000.csv', index_col=False), ignore_index=True)
data = data.append(pd.read_csv('data/poet220000.csv', index_col=False), ignore_index=True)
data = data.append(pd.read_csv('data/poet240000.csv', index_col=False), ignore_index=True)
data = data.append(pd.read_csv('data/poet260000.csv', index_col=False), ignore_index=True)
data = data.append(pd.read_csv('data/poet280000.csv', index_col=False), ignore_index=True)
data = data.append(pd.read_csv('data/poet300000.csv', index_col=False), ignore_index=True)

# d2 = pd.read_csv('data/poet20000.csv', index_col=False)
# d3 = pd.read_csv('data/poet40000.csv', index_col=False)
# d4 = pd.read_csv('data/poet60000.csv', index_col=False)
# d3 = pd.read_csv('data/poet80000.csv', index_col=False)
# d3 = pd.read_csv('data/poet100000.csv', index_col=False)
# d3 = pd.read_csv('data/poet120000.csv', index_col=False)
# d3 = pd.read_csv('data/poet140000.csv', index_col=False)
# d3 = pd.read_csv('data/poet160000.csv', index_col=False)
# d3 = pd.read_csv('data/poet180000.csv', index_col=False)
# d3 = pd.read_csv('data/poet200000.csv', index_col=False)
# d3 = pd.read_csv('data/poet220000.csv', index_col=False)
# d3 = pd.read_csv('data/poet240000.csv', index_col=False)
# d3 = pd.read_csv('data/poet260000.csv', index_col=False)
# d3 = pd.read_csv('data/poet280000.csv', index_col=False)
# d3 = pd.read_csv('data/poet300000.csv', index_col=False)


# data = data.append(d2, ignore_index=True)
# data = data.append(d3, ignore_index=True)

data.to_csv('data/delete.csv', index=False)

print("merge data")
print(data.info())
print(data.describe())    
